// Code generated by oapi-ginx; DO NOT EDIT.

package sseops

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/chendefine/ginx"
	"resty.dev/v3"
)

type ClientOption func(*resty.Client)

type ClientInterface interface {
	StreamEvents(ctx context.Context, req *StreamEventsReq) (*ginx.SSEStream, error)
	StreamMetrics(ctx context.Context, req *StreamMetricsReq) (*ginx.SSEStream, error)
	StreamNotifications(ctx context.Context, req *StreamNotificationsReq) (*ginx.SSEStream, error)
	StreamRoomMessages(ctx context.Context, req *StreamRoomMessagesReq) (*ginx.SSEStream, error)
}

type Client struct {
	client *resty.Client
}

func NewClient(baseURL string, opts ...ClientOption) *Client {
	c := resty.New().SetBaseURL(baseURL)
	for _, opt := range opts {
		opt(c)
	}
	return &Client{client: c}
}

func (c *Client) StreamEvents(ctx context.Context, req *StreamEventsReq) (*ginx.SSEStream, error) {
	sseURL := c.client.BaseURL() + "/events/stream"

	q := make(url.Values)
	q.Set("channel", req.Channel)
	if req.LastEventID != nil {
		q.Set("last_event_id", *req.LastEventID)
	}
	if encoded := q.Encode(); encoded != "" {
		sseURL += "?" + encoded
	}

	es := resty.NewSSESource()
	es.SetURL(sseURL)

	return ginx.NewSSEStream(ctx, es), nil
}

func (c *Client) StreamMetrics(ctx context.Context, req *StreamMetricsReq) (*ginx.SSEStream, error) {
	sseURL := c.client.BaseURL() + "/metrics"

	es := resty.NewSSESource()
	es.SetURL(sseURL)

	return ginx.NewSSEStream(ctx, es), nil
}

func (c *Client) StreamNotifications(ctx context.Context, req *StreamNotificationsReq) (*ginx.SSEStream, error) {
	sseURL := c.client.BaseURL() + "/notifications"

	q := make(url.Values)
	if req.Types != nil {
		q.Set("types", *req.Types)
	}
	if encoded := q.Encode(); encoded != "" {
		sseURL += "?" + encoded
	}

	es := resty.NewSSESource()
	es.SetURL(sseURL)

	es.SetHeader("X-Auth-Token", req.XAuthToken)

	return ginx.NewSSEStream(ctx, es), nil
}

func (c *Client) StreamRoomMessages(ctx context.Context, req *StreamRoomMessagesReq) (*ginx.SSEStream, error) {
	sseURL := c.client.BaseURL() + "/rooms/{room_id}/messages"

	sseURL = strings.Replace(sseURL, "{room_id}", url.PathEscape(req.RoomID), 1)

	q := make(url.Values)
	if req.Since != nil {
		q.Set("since", req.Since.Format(time.RFC3339))
	}
	if encoded := q.Encode(); encoded != "" {
		sseURL += "?" + encoded
	}

	es := resty.NewSSESource()
	es.SetURL(sseURL)

	es.SetHeader("X-Auth-Token", req.XAuthToken)

	return ginx.NewSSEStream(ctx, es), nil
}
