// Code generated by oapi-ginx; DO NOT EDIT.

package sseops

import (
	"context"

	"github.com/chendefine/ginx"
	"github.com/gin-gonic/gin"
)

type ServerInterface interface {
	// GET /events/stream
	StreamEvents(ctx context.Context, req *StreamEventsReq, send ginx.Sender) error
	// GET /metrics
	StreamMetrics(ctx context.Context, req *StreamMetricsReq, send ginx.Sender) error
	// GET /notifications
	StreamNotifications(ctx context.Context, req *StreamNotificationsReq, send ginx.Sender) error
	// GET /rooms/:room_id/messages
	StreamRoomMessages(ctx context.Context, req *StreamRoomMessagesReq, send ginx.Sender) error
}

func RegisterRoutes(r gin.IRoutes, s ServerInterface, opts ...ginx.RouteOption) {
	ginx.SSE(r, "/events/stream", s.StreamEvents, opts...)
	ginx.SSE(r, "/metrics", s.StreamMetrics, opts...)
	ginx.SSE(r, "/notifications", s.StreamNotifications, opts...)
	ginx.SSE(r, "/rooms/:room_id/messages", s.StreamRoomMessages, opts...)
}
