// Code generated by oapi-ginx; DO NOT EDIT.

package sseops

import (
	"time"
)

type StreamEventsReq struct {
	Channel     string  `form:"channel" binding:"required"`
	LastEventID *string `form:"last_event_id"`
}

type StreamMetricsReq struct {
}

type StreamNotificationsReq struct {
	XAuthToken string  `header:"X-Auth-Token" binding:"required"`
	Types      *string `form:"types"`
}

type StreamRoomMessagesReq struct {
	RoomID     string     `uri:"room_id" binding:"required"`
	Since      *time.Time `form:"since"`
	XAuthToken string     `header:"X-Auth-Token" binding:"required"`
}
