// Code generated by oapi-ginx; DO NOT EDIT.

package querystring

import (
	"context"
	"fmt"

	"github.com/chendefine/ginx"
	"resty.dev/v3"
)

type ClientOption func(*resty.Client)

type ClientInterface interface {
	Search(ctx context.Context, req *SearchReq) (*SearchRsp, error)
}

type Client struct {
	client *resty.Client
}

func NewClient(baseURL string, opts ...ClientOption) *Client {
	c := resty.New().SetBaseURL(baseURL)
	for _, opt := range opts {
		opt(c)
	}
	return &Client{client: c}
}

func (c *Client) Search(ctx context.Context, req *SearchReq) (*SearchRsp, error) {
	r := c.client.R().SetContext(ctx)

	r.SetQueryParam("q", req.Q)
	if req.Limit != nil {
		r.SetQueryParam("limit", fmt.Sprintf("%d", *req.Limit))
	}

	resp, err := r.Get("/search")
	if err != nil {
		return nil, err
	}

	var result SearchRsp
	if err := ginx.ParseResponse(resp.StatusCode(), resp.Bytes(), &result); err != nil {
		return nil, err
	}
	return &result, nil
}
