// Code generated by oapi-ginx; DO NOT EDIT.

package querystring

import (
	"context"

	"github.com/chendefine/ginx"
	"github.com/gin-gonic/gin"
)

type ServerInterface interface {
	// GET /search
	Search(ctx context.Context, req *SearchReq) (*SearchRsp, error)
}

func RegisterRoutes(r gin.IRoutes, s ServerInterface, opts ...ginx.RouteOption) {
	ginx.GET(r, "/search", s.Search, opts...)
}
