// Code generated by oapi-ginx; DO NOT EDIT.

package querystring

type SearchReq struct {
	Q     string `form:"q" binding:"required"`
	Limit *int   `form:"limit"`
}

type SearchRsp struct {
	Limit *int    `json:"limit"`
	Q     *string `json:"q"`
}
