// Code generated by oapi-ginx; DO NOT EDIT.

package jsonlines

import (
	"context"
	"fmt"
	"io"

	"github.com/chendefine/ginx"
	"resty.dev/v3"
)

type ClientOption func(*resty.Client)

type ClientInterface interface {
	IngestBatch(ctx context.Context, req *IngestBatchReq) (*ginx.JSONLinesStream, error)
	TailLogs(ctx context.Context, req *TailLogsReq) (*ginx.JSONLinesStream, error)
}

type Client struct {
	client *resty.Client
}

func NewClient(baseURL string, opts ...ClientOption) *Client {
	c := resty.New().SetBaseURL(baseURL)
	for _, opt := range opts {
		opt(c)
	}
	return &Client{client: c}
}

func (c *Client) IngestBatch(ctx context.Context, req *IngestBatchReq) (*ginx.JSONLinesStream, error) {
	r := c.client.R().SetContext(ctx).SetResponseDoNotParse(true)

	r.SetBody(req)

	resp, err := r.Post("/ingest")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		return nil, &ginx.ErrWrap{Code: -1, Msg: string(body), HttpCode: resp.StatusCode()}
	}
	return ginx.NewJSONLinesStream(ctx, resp.Body), nil
}

func (c *Client) TailLogs(ctx context.Context, req *TailLogsReq) (*ginx.JSONLinesStream, error) {
	r := c.client.R().SetContext(ctx).SetResponseDoNotParse(true)

	r.SetPathParam("source", req.Source)

	if req.Follow != nil {
		r.SetQueryParam("follow", fmt.Sprintf("%t", *req.Follow))
	}

	if req.XTraceID != nil {
		r.SetHeader("X-Trace-Id", *req.XTraceID)
	}

	resp, err := r.Get("/logs/{source}/tail")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		return nil, &ginx.ErrWrap{Code: -1, Msg: string(body), HttpCode: resp.StatusCode()}
	}
	return ginx.NewJSONLinesStream(ctx, resp.Body), nil
}
