// Code generated by oapi-ginx; DO NOT EDIT.

package jsonlines

import (
	"context"

	"github.com/chendefine/ginx"
	"github.com/gin-gonic/gin"
)

type ServerInterface interface {
	// POST /ingest
	IngestBatch(ctx context.Context, req *IngestBatchReq, send ginx.JSONLinesSender) error
	// GET /logs/:source/tail
	TailLogs(ctx context.Context, req *TailLogsReq, send ginx.JSONLinesSender) error
}

func RegisterRoutes(r gin.IRoutes, s ServerInterface, opts ...ginx.RouteOption) {
	ginx.JSONLines(r, "POST", "/ingest", s.IngestBatch, opts...)
	ginx.JSONLines(r, "GET", "/logs/:source/tail", s.TailLogs, opts...)
}
