// Code generated by oapi-ginx; DO NOT EDIT.

package jsonlines

type IngestBatchReq struct {
	Count int `json:"count" binding:"required"`
}

type TailLogsReq struct {
	Source   string  `uri:"source" binding:"required"`
	Follow   *bool   `form:"follow"`
	XTraceID *string `header:"X-Trace-Id"`
}
